#!/bin/bash
current_branch=`git branch | grep '*' | sed 's/* //'`
green=`tput setaf 2`
reset=`tput sgr0`
red=`tput setaf 1`
yellow='\033[1;33m'

printf "\nVerificando seu commit no branch ${green} $current_branch ${reset} (: Aguarde...."
printf "\n${red}Formatando o código.........${reset}\n"
flutter format . --set-exit-if-changed
status=$?
if [ $status -eq 1 ]; then
    printf "\n${yellow}Arquivos foram formatados, verifique-os e tente novamente.${reset}\n"
    exit 1
fi

printf "\n${yellow}Aplicando o Lint.....${reset}\n"
flutter analyze

if [ $? -ne 0 ]; then
        printf "\n${red}Eita, algo de errado não está certo ):${reset}\n"
        exit 1
fi
